# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A12M22m0Sg1pZwLPFLTAcjJqHika-gkf
"""

import random
lower = "abcdefghijklmnopqrstuvwxyz"
upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
numbers = "0123456789"
symbols = "!@#$%^&*()_-+=?><["
all_chars = lower+upper+numbers+symbols
length = int(input("enter a length: "))
password = ''.join(random.sample(all_chars, length))
print("Generated password:", password)